conditions: v1

git:
  depth: 99999

dist: focal

language: java

jdk:
  - openjdk11

addons:
  apt:
    update: true
  chrome: stable
  firefox: latest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

jobs:
  include:
    - script: ./gradlew classes --no-daemon --console=plain
      name: "Compile"
    - script: ./gradlew firefox_headless --no-daemon --console=plain -i --fail-fast
      name: "Firefox 1"
    - script: ./gradlew firefox_headless --no-daemon --console=plain -i --fail-fast
      name: "Firefox 2"
    - script: ./gradlew firefox_headless --no-daemon --console=plain -i --fail-fast
      name: "Firefox 3"
    - script: ./gradlew firefox_headless --no-daemon --console=plain -i --fail-fast
      name: "Firefox 4"
    - script: ./gradlew chrome_headless --no-daemon --console=plain -i --fail-fast
      name: "Chrome 1"
    - script: ./gradlew chrome_headless --no-daemon --console=plain -i --fail-fast
      name: "Chrome 2"

after_failure: "./.upload_reports.sh"
